---
# handlers/main.yml

- name: Restart dnf-automatic service
  ansible.builtin.systemd_service:
    name: dnf-automatic.timer
    state: restarted

- name: Restart dnf5-automatic service
  ansible.builtin.systemd_service:
    name: dnf5-automatic.timer
    state: restarted

- name: Restart yum-cron service
  ansible.builtin.systemd_service:
    name: yum-cron.service
    state: restarted
