---
- name: Converge
  hosts: all
  gather_facts: true
  become: false
  vars:
    au_enable_auto_update: true
    au_security_only: true
    au_email_from: root
    au_email_to: admin@someorg.local
    au_download_only: false
    au_emit_via: stdio
    au_email_server: localhost
    au_system_name: mysystem
    au_mail_report: only-on-error
    au_remove_old_kernel: true
    au_remove_new_unused_dependencies: true
    au_remove_unused_dependencies: false
    au_automatic_reboot: false
    au_reboot_with_users: true
    au_reboot_time: '02:00'
    au_syslog_enable: false
    au_syslog_facility: daemon
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
